FacturApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
    SubcategoriaView, SubcategoriaNew, SubcategoriaEdit, SubcategoriaDel, \
    MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
    UnidadMedidaView, UnidadMedidaNew, UnidadMedidaEdit, unidadmedida_inactivar

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/', SubcategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubcategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubcategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubcategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/', MarcaView.as_view(), name='marca_list'),
    path('marcas/new', MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/inactivar/<int:id>', marca_inactivar, name='marca_inactivar'),

    path('unidades-medida/', UnidadMedidaView.as_view(), name='unidadmedida_list'),
    path('unidades-medida/new', UnidadMedidaNew.as_view(), name='unidadmedida_new'),
    path('unidades-medida/edit/<int:pk>', UnidadMedidaEdit.as_view(), name='unidadmedida_edit'),
    path('unidades-medida/inactivar/<int:id>', unidadmedida_inactivar, name='unidadmedida_inactivar'),
]

bases/models.py
from django.db import models
from django.contrib.auth.models import User

class Modelo(models.Model):
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modifica = models.DateTimeField(auto_now=True)
    user_creacion = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        # colocamos %(class)s delante de cada relate_name para evitar colisiones
        # al heredar los hijos
        related_name='%(class)s_User_Create',
        verbose_name = 'Creado por',
    )

    user_modifica = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        related_name='%(class)s_User_Update',
        verbose_name = 'Modificado por',
        blank = True, 
        null = True,
    )

    # con astract=True, le decimos que no tenga en cuenta el model para las migraciones
    class Meta:
        abstract = True

inv/models.py
from django.db import models
from bases.models import Modelo

class Categoria(Modelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción',
        unique=True, 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    # sobreescribimos el mètodo save para guardar la descripción en mayúsculas
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = 'Categorías'


class Subcategoria(Modelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción',
        unique=True, 
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    # sobreescribimos el mètodo save para guardar la descripción en mayúsculas
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Subcategoria, self).save()
    
    class Meta:
        verbose_name_plural = 'Subcategorías'
        # Evitamos que se repitan las subcategorias dentro de cada categoria
        # no podemos usar unique porque pueden repetirse dentro de diferentes
        # Categorias, por ej, todas las categorias pueden tener un "todos"
        unique_together = ('categoria', 'descripcion')


class Marca(Modelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción',
        unique=True, 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    # sobreescribimos el mètodo save para guardar la descripción en mayúsculas
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = 'Marcas'


class UnidadMedida(Modelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción',
        unique=True, 
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    # sobreescribimos el mètodo save para guardar la descripción en mayúsculas
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida, self).save()

    class Meta:
        verbose_name_plural = 'Unidades de Medida'

inv/forms.py
from django import forms
from .models import Categoria, Subcategoria, Marca, UnidadMedida

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripción', 'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    # sobreescribo el método init para asignar la class a todos el elementos del form
    # también puede hacerse con cada elemento 
    # widget = {'descripcion': forms.TextInput(attrs={'class':'form-control'})}
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })


class SubcategoriaForm(forms.ModelForm):
    # modificamos el queryset para que sólo muestre los activos
    categoria = forms.ModelChoiceField(
        queryset = Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )
    class Meta:
        model = Subcategoria
        fields = ['categoria', 'descripcion', 'estado']
        labels = {'descripcion':'Sub Categoría', 'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    # sobreescribo el método init para asignar la class a todos el elementos del form
    # también puede hacerse con cada elemento 
    # widget = {'descripcion': forms.TextInput(attrs={'class':'form-control'})}
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })
        
        self.fields['categoria'].empty_label = 'Seleecione categoría'


class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripción', 'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    # sobreescribo el método init para asignar la class a todos el elementos del form
    # también puede hacerse con cada elemento 
    # widget = {'descripcion': forms.TextInput(attrs={'class':'form-control'})}
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })

class UnidadMedidaForm(forms.ModelForm):
    class Meta:
        model = UnidadMedida
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripción', 'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    # sobreescribo el método init para asignar la class a todos el elementos del form
    # también puede hacerse con cada elemento 
    # widget = {'descripcion': forms.TextInput(attrs={'class':'form-control'})}
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })

inv/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Categoria, Subcategoria, Marca, UnidadMedida
from .forms import CategoriaForm, SubcategoriaForm, MarcaForm, UnidadMedidaForm

class CategoriaView(LoginRequiredMixin, ListView):
    model = Categoria
    # no hace falta lo que sigue abajo ya que uso los 
    # template_name y context_object_name que toma por defecto: 
    # className_list.html y className_list respectivamente
    # template_name = "inv/categoria_list.html"
    # context_object_name = "obj"
    login_url = 'bases:login'


class CategoriaNew(LoginRequiredMixin, CreateView):
    model = Categoria
    # template_name = 'inv/categoria_form.html'
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    login_url = 'bases:login'

    # modificamos el form en el form_valid para guardar el usuario
    def form_valid(self, form):
        form.instance.user_creacion = self.request.user
        return super().form_valid(form)


class CategoriaEdit(LoginRequiredMixin, UpdateView):
    model = Categoria
    # template_name = 'inv/categoria_form.html'
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    login_url = 'bases:login'

    # modificamos el form en el form_valid para guardar el usuario
    def form_valid(self, form):
        form.instance.user_modifica = self.request.user
        return super().form_valid(form)


class CategoriaDel(LoginRequiredMixin, DeleteView):
    model = Categoria
    template_name = 'inv/catalogo_del.html'
    # como el template de borrado es genérico para varias objetos del catálogo 
    # llamo obj_del al objeto
    context_object_name = 'obj_del'
    success_url = reverse_lazy('inv:categoria_list')
    login_url = 'bases:login'


class SubcategoriaView(LoginRequiredMixin, ListView):
    model = Subcategoria
    login_url = 'bases:login'


class SubcategoriaNew(LoginRequiredMixin, CreateView):
    model = Subcategoria
    form_class = SubcategoriaForm
    success_url = reverse_lazy('inv:subcategoria_list')
    login_url = 'bases:login'

    # modificamos el form en el form_valid para guardar el usuario
    def form_valid(self, form):
        form.instance.user_creacion = self.request.user
        return super().form_valid(form)


class SubcategoriaEdit(LoginRequiredMixin, UpdateView):
    model = Subcategoria
    form_class = SubcategoriaForm
    success_url = reverse_lazy('inv:subcategoria_list')
    login_url = 'bases:login'

    # modificamos el form en el form_valid para guardar el usuario
    def form_valid(self, form):
        form.instance.user_modifica = self.request.user
        return super().form_valid(form)

class SubcategoriaDel(LoginRequiredMixin, DeleteView):
    model = Subcategoria
    template_name = 'inv/catalogo_del.html'
    context_object_name = 'obj_del'
    success_url = reverse_lazy('inv:subcategoria_list')
    login_url = 'bases:login'


class MarcaView(LoginRequiredMixin, ListView):
    model = Marca
    # no hace falta lo que sigue abajo ya que uso los 
    # template_name y context_object_name que toma por defecto: 
    # className_list.html y className_list respectivamente
    # template_name = "inv/categoria_list.html"
    # context_object_name = "obj"
    login_url = 'bases:login'

class MarcaNew(LoginRequiredMixin, CreateView):
    model = Marca
    # template_name = 'inv/categoria_form.html'
    form_class = MarcaForm
    success_url = reverse_lazy('inv:marca_list')
    login_url = 'bases:login'

    # modificamos el form en el form_valid para guardar el usuario
    def form_valid(self, form):
        form.instance.user_creacion = self.request.user
        return super().form_valid(form)

class MarcaEdit(LoginRequiredMixin, UpdateView):
    model = Marca
    # template_name = 'inv/categoria_form.html'
    form_class = MarcaForm
    success_url = reverse_lazy('inv:marca_list')
    login_url = 'bases:login'

    # modificamos el form en el form_valid para guardar el usuario
    def form_valid(self, form):
        form.instance.user_modifica = self.request.user
        return super().form_valid(form)


# Para inactivar usaremos vistas basadas en funciones
def marca_inactivar(request, id):
    marca = Marca.objects.filter(pk=id).first()
    contexto =  {}
    template = "inv/catalogo_del.html"

    if not marca:
        return redirect("inv:marca_list")
    
    if request.method == 'GET':
        contexto = {'obj_del':marca}
    
    if request.method == 'POST':
        marca.estado = False
        marca.save()
        return redirect("inv:marca_list")
    
    return render(request, template, contexto)


class UnidadMedidaView(LoginRequiredMixin, ListView):
    model = UnidadMedida
    login_url = 'bases:login'

class UnidadMedidaNew(LoginRequiredMixin, CreateView):
    model = UnidadMedida
    form_class = UnidadMedidaForm
    success_url = reverse_lazy('inv:unidadmedida_list')
    login_url = 'bases:login'

    # modificamos el form en el form_valid para guardar el usuario
    def form_valid(self, form):
        form.instance.user_creacion = self.request.user
        return super().form_valid(form)

class UnidadMedidaEdit(LoginRequiredMixin, UpdateView):
    model = UnidadMedida
    # template_name = 'inv/categoria_form.html'
    form_class = UnidadMedidaForm
    success_url = reverse_lazy('inv:unidadmedida_list')
    login_url = 'bases:login'

    # modificamos el form en el form_valid para guardar el usuario
    def form_valid(self, form):
        form.instance.user_modifica = self.request.user
        return super().form_valid(form)

def unidadmedida_inactivar(request, id):
    unida_medida = UnidadMedida.objects.filter(pk=id).first()
    contexto =  {}
    template = "inv/catalogo_del.html"

    if not unida_medida:
        return redirect("inv:unidadmedida_list")
    
    if request.method == 'GET':
        contexto = {'obj_del':unida_medida}
    
    if request.method == 'POST':
        unida_medida.estado = False
        unida_medida.save()
        return redirect("inv:unidadmedida_list")
    
    return render(request, template, contexto)

inv/templates/inv/categoria_form.html
{% extends "base/base.html" %}
{% block page_content %}

 <form action="" method="POST" class="form-inline">
    {% csrf_token %}
     <div class="container-fluid">
        <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Categorías</h1>
          </div>
          <div class="row">
            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-6 mb-6">
              <div class="card border-left-{% if categoria %}warning{% else %}success{% endif %} shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-{% if categoria %}warning{% else %}success{% endif %} text-uppercase mb-1">
                            {% if categoria %}Editar{% else %}Alta{% endif %} de Categoría
                        </div>

                        </div>
                        <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>

                    </div>

                    <div class="dropdown-divider"></div>

                    <div class="row">
                    
                        <div class="col-10">
                            <div class="input-group">
                                <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción" value="{% if categoria %} {{ categoria.descripcion }}{% endif %}">
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if categoria.estado %} checked{% endif %}>
                            </div>
                        </div>
                   
                        {% comment %} {{ form.as_p }}  {% endcomment %}
                    </div>

                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col-10">
                        <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>Guardar</button>
                        <a href="{% url 'inv:categoria_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                </div>

                </div>
              </div>
            </div>

            <!-- Pending Requests Card Example -->

          </div>

    <div class="row">

            <div class="col-lg-6"></div>

            <div class="col-lg-6"></div>

   </div>
</div>
</form>
<br><br><br><br>
{% endblock page_content %}

inv/templates/inv/categoria_list.html
{% extends "base/base.html" %}

{% block page_content %}
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Listado de Categorías</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
              <div class="dropdown-header">Acciones:</div>
              <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Agregar</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          {% if not categoria_list %}
            <div class="alert alert-info">No existen Categorías</div>
          {% else %}
          <table class="table table-striped table-hover">
              <thead>
                  <th>ID</th>
                  <th>Descripción</th>
                  <th>Estado</th>
                  <th>Fecha creación</th>
                  <th>Fecha modif.</th>
                  <!-- class all hace que la columna se muestre siempre -->
                  <th class="all">Acciones</th>
              </thead>
              <tbody>
                  {% for item in categoria_list %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>{{ item.fecha_creacion|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fecha_modifica|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:categoria_edit' pk=item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:categoria_del' pk=item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
          {% endif %}
        </div>
      </div>
{% endblock page_content %}

{% block js_page %}
<script>
    $(document).ready(function(){
      $('.table').DataTable();
    })
</script>
{% endblock js_page %}

inv/templates/inv/marca_list.html
{% extends "base/base.html" %}

{% block page_content %}
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Listado de Marcas</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
              <div class="dropdown-header">Acciones:</div>
              <a class="dropdown-item" href="{% url 'inv:marca_new' %}"><i class="far fa-calendar-plus"></i> Agregar</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          {% if not marca_list %}
            <div class="alert alert-info">No existen Marcas</div>
          {% else %}
          <table class="table table-striped table-hover">
              <thead>
                  <th>ID</th>
                  <th>Descripción</th>
                  <th>Estado</th>
                  <th>Fecha creación</th>
                  <th>Fecha modif.</th>
                  <!-- class all hace que la columna se muestre siempre -->
                  <th class="all">Acciones</th>
              </thead>
              <tbody>
                  {% for item in marca_list %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>{{ item.fecha_creacion|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fecha_modifica|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:marca_edit' pk=item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:marca_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
          {% endif %}
        </div>
      </div>
{% endblock page_content %}

{% block js_page %}
<script>
    $(document).ready(function(){
      $('.table').DataTable();
    })
</script>
{% endblock js_page %}

inv/templates/inv/subcategoria_list.html
{% extends "base/base.html" %}

{% block page_content %}
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Listado de SubCategorías</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
              <div class="dropdown-header">Acciones:</div>
              <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="far fa-calendar-plus"></i> Agregar</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          {% if not subcategoria_list %}
            <div class="alert alert-info">No existen SubCategorías</div>
          {% else %}
          <table class="table table-striped table-hover">
              <thead>
                  <th>Categoría</th>
                  <th>ID</th>
                  <th>Descripción</th>
                  <th>Estado</th>
                  <th>Fecha creación</th>
                  <th>Fecha modif.</th>
                  <!-- class all hace que la columna se muestre siempre -->
                  <th class="all">Acciones</th>
              </thead>
              <tbody>
                  {% for item in subcategoria_list %}
                    <tr>
                        <td>{{ item.categoria }}</td>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>{{ item.fecha_creacion|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fecha_modifica|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:subcategoria_edit' pk=item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:subcategoria_del' pk=item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
          {% endif %}
        </div>
      </div>
{% endblock page_content %}

{% block js_page %}
<script>
    $(document).ready(function(){
      $('.table').DataTable();
    })
</script>
{% endblock js_page %}

inv/templates/inv/unidadmedida_list.html
{% extends "base/base.html" %}

{% block page_content %}
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Listado de Unidades de Medida</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
              <div class="dropdown-header">Acciones:</div>
              <a class="dropdown-item" href="{% url 'inv:unidadmedida_new' %}"><i class="far fa-calendar-plus"></i> Agregar</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          {% if not unidadmedida_list %}
            <div class="alert alert-info">No existen Unidades de Medida</div>
          {% else %}
          <table class="table table-striped table-hover">
              <thead>
                  <th>ID</th>
                  <th>Descripción</th>
                  <th>Estado</th>
                  <th>Fecha creación</th>
                  <th>Fecha modif.</th>
                  <!-- class all hace que la columna se muestre siempre -->
                  <th class="all">Acciones</th>
              </thead>
              <tbody>
                  {% for item in unidadmedida_list %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>{{ item.fecha_creacion|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fecha_modifica|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:unidadmedida_edit' pk=item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:unidadmedida_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
          {% endif %}
        </div>
      </div>
{% endblock page_content %}

{% block js_page %}
<script>
    $(document).ready(function(){
      $('.table').DataTable();
    })
</script>
{% endblock js_page %}